type t

val of_int : int -> t
val to_int : t -> int

val eperm           : t  (* Operation not permitted *)
val enoent          : t  (* No such file or directory *)
val esrch           : t  (* No such process *)
val eintr           : t  (* Interrupted system call *)
val eio             : t  (* I/O error *)
val enxio           : t  (* No such device or address *)
val e2big           : t  (* Argument list too long *)
val enoexec         : t  (* Exec format error *)
val ebadf           : t  (* Bad file number *)
val echild          : t  (* No child processes *)
val eagain          : t  (* Try again *)
val enomem          : t  (* Out of memory *)
val eacces          : t  (* Permission denied *)
val efault          : t  (* Bad address *)
val enotblk         : t  (* Block device required *)
val ebusy           : t  (* Device or resource busy *)
val eexist          : t  (* File exists *)
val exdev           : t  (* Cross-device link *)
val enodev          : t  (* No such device *)
val enotdir         : t  (* Not a directory *)
val eisdir          : t  (* Is a directory *)
val einval          : t  (* Invalid argument *)
val enfile          : t  (* File table overflow *)
val emfile          : t  (* Too many open files *)
val enotty          : t  (* Not a typewriter *)
val etxtbsy         : t  (* Text file busy *)
val efbig           : t  (* File too large *)
val enospc          : t  (* No space left on device *)
val espipe          : t  (* Illegal seek *)
val erofs           : t  (* Read-only file system *)
val emlink          : t  (* Too many links *)
val epipe           : t  (* Broken pipe *)
val edom            : t  (* Math argument out of domain of func *)
val erange          : t  (* Math result not representable *)
val edeadlk         : t  (* Resource deadlock would occur *)
val enametoolong    : t  (* File name too long *)
val enolck          : t  (* No record locks available *)
val enosys          : t  (* Invalid system call number *)
val enotempty       : t  (* Directory not empty *)
val eloop           : t  (* Too many symbolic links encountered *)
val ewouldblock     : t  (* Operation would block (= eagain) *)
val enomsg          : t  (* No message of desired type *)
val eidrm           : t  (* Identifier removed *)
val echrng          : t  (* Channel number out of range *)
val el2nsync        : t  (* Level 2 not synchronized *)
val el3hlt          : t  (* Level 3 halted *)
val el3rst          : t  (* Level 3 reset *)
val elnrng          : t  (* Link number out of range *)
val eunatch         : t  (* Protocol driver not attached *)
val enocsi          : t  (* No CSI structure available *)
val el2hlt          : t  (* Level 2 halted *)
val ebade           : t  (* Invalid exchange *)
val ebadr           : t  (* Invalid request descriptor *)
val exfull          : t  (* Exchange full *)
val enoano          : t  (* No anode *)
val ebadrqc         : t  (* Invalid request code *)
val ebadslt         : t  (* Invalid slot *)
val edeadlock       : t  (* Resource deadlock would occur (= edeadlk) *)
val ebfont          : t  (* Bad font file format *)
val enostr          : t  (* Device not a stream *)
val enodata         : t  (* No data available *)
val etime           : t  (* Timer expired *)
val enosr           : t  (* Out of streams resources *)
val enonet          : t  (* Machine is not on the network *)
val enopkg          : t  (* Package not installed *)
val eremote         : t  (* Object is remote *)
val enolink         : t  (* Link has been severed *)
val eadv            : t  (* Advertise error *)
val esrmnt          : t  (* Srmount error *)
val ecomm           : t  (* Communication error on send *)
val eproto          : t  (* Protocol error *)
val emultihop       : t  (* Multihop attempted *)
val edotdot         : t  (* RFS specific error *)
val ebadmsg         : t  (* Not a data message *)
val eoverflow       : t  (* Value too large for defined data type *)
val enotuniq        : t  (* Name not unique on network *)
val ebadfd          : t  (* File descriptor in bad state *)
val eremchg         : t  (* Remote address changed *)
val elibacc         : t  (* Can not access a needed shared library *)
val elibbad         : t  (* Accessing a corrupted shared library *)
val elibscn         : t  (* .lib section in a.out corrupted *)
val elibmax         : t  (* Attempting to link in too many shared libraries *)
val elibexec        : t  (* Cannot exec a shared library directly *)
val eilseq          : t  (* Illegal byte sequence *)
val erestart        : t  (* Interrupted system call should be restarted *)
val estrpipe        : t  (* Streams pipe error *)
val eusers          : t  (* Too many users *)
val enotsock        : t  (* Socket operation on non-socket *)
val edestaddrreq    : t  (* Destination address required *)
val emsgsize        : t  (* Message too long *)
val eprototype      : t  (* Protocol wrong type for socket *)
val enoprotoopt     : t  (* Protocol not available *)
val eprotonosupport : t  (* Protocol not supported *)
val esocktnosupport : t  (* Socket type not supported *)
val eopnotsupp      : t  (* Operation not supported on transport endpoint *)
val enotsup         : t  (* Operation not supported (= eopnotsupp) *)
val epfnosupport    : t  (* Protocol family not supported *)
val eafnosupport    : t  (* Address family not supported by protocol *)
val eaddrinuse      : t  (* Address already in use *)
val eaddrnotavail   : t  (* Cannot assign requested address *)
val enetdown        : t  (* Network is down *)
val enetunreach     : t  (* Network is unreachable *)
val enetreset       : t  (* Network dropped connection because of reset *)
val econnaborted    : t  (* Software caused connection abort *)
val econnreset      : t  (* Connection reset by peer *)
val enobufs         : t  (* No buffer space available *)
val eisconn         : t  (* Transport endpoint is already connected *)
val enotconn        : t  (* Transport endpoint is not connected *)
val eshutdown       : t  (* Cannot send after transport endpoint shutdown *)
val etoomanyrefs    : t  (* Too many references: cannot splice *)
val etimedout       : t  (* Connection timed out *)
val econnrefused    : t  (* Connection refused *)
val ehostdown       : t  (* Host is down *)
val ehostunreach    : t  (* No route to host *)
val ealready        : t  (* Operation already in progress *)
val einprogress     : t  (* Operation now in progress *)
val estale          : t  (* Stale file handle *)
val euclean         : t  (* Structure needs cleaning *)
val enotnam         : t  (* Not a XENIX named type file *)
val enavail         : t  (* No XENIX semaphores available *)
val eisnam          : t  (* Is a named type file *)
val eremoteio       : t  (* Remote I/O error *)
val edquot          : t  (* Quota exceeded *)
val enomedium       : t  (* No medium found *)
val emediumtype     : t  (* Wrong medium type *)
val ecanceled       : t  (* Operation Canceled *)
val enokey          : t  (* Required key not available *)
val ekeyexpired     : t  (* Key has expired *)
val ekeyrevoked     : t  (* Key has been revoked *)
val ekeyrejected    : t  (* Key was rejected by service *)
val eownerdead      : t  (* Owner died *)
val enotrecoverable : t  (* State not recoverable *)
val erfkill         : t  (* Operation not possible due to RF-kill *)
val ehwpoison       : t  (* Memory page has hardware error *)
