#define CAML_NAME_SPACE
#include <caml/mlvalues.h>

#include <errno.h>

CAMLprim value hemlock__c__errno__eperm(value unit)           { (void)unit; return Val_int(EPERM); }
CAMLprim value hemlock__c__errno__enoent(value unit)          { (void)unit; return Val_int(ENOENT); }
CAMLprim value hemlock__c__errno__esrch(value unit)           { (void)unit; return Val_int(ESRCH); }
CAMLprim value hemlock__c__errno__eintr(value unit)           { (void)unit; return Val_int(EINTR); }
CAMLprim value hemlock__c__errno__eio(value unit)             { (void)unit; return Val_int(EIO); }
CAMLprim value hemlock__c__errno__enxio(value unit)           { (void)unit; return Val_int(ENXIO); }
CAMLprim value hemlock__c__errno__e2big(value unit)           { (void)unit; return Val_int(E2BIG); }
CAMLprim value hemlock__c__errno__enoexec(value unit)         { (void)unit; return Val_int(ENOEXEC); }
CAMLprim value hemlock__c__errno__ebadf(value unit)           { (void)unit; return Val_int(EBADF); }
CAMLprim value hemlock__c__errno__echild(value unit)          { (void)unit; return Val_int(ECHILD); }
CAMLprim value hemlock__c__errno__eagain(value unit)          { (void)unit; return Val_int(EAGAIN); }
CAMLprim value hemlock__c__errno__enomem(value unit)          { (void)unit; return Val_int(ENOMEM); }
CAMLprim value hemlock__c__errno__eacces(value unit)          { (void)unit; return Val_int(EACCES); }
CAMLprim value hemlock__c__errno__efault(value unit)          { (void)unit; return Val_int(EFAULT); }
CAMLprim value hemlock__c__errno__enotblk(value unit)         { (void)unit; return Val_int(ENOTBLK); }
CAMLprim value hemlock__c__errno__ebusy(value unit)           { (void)unit; return Val_int(EBUSY); }
CAMLprim value hemlock__c__errno__eexist(value unit)          { (void)unit; return Val_int(EEXIST); }
CAMLprim value hemlock__c__errno__exdev(value unit)           { (void)unit; return Val_int(EXDEV); }
CAMLprim value hemlock__c__errno__enodev(value unit)          { (void)unit; return Val_int(ENODEV); }
CAMLprim value hemlock__c__errno__enotdir(value unit)         { (void)unit; return Val_int(ENOTDIR); }
CAMLprim value hemlock__c__errno__eisdir(value unit)          { (void)unit; return Val_int(EISDIR); }
CAMLprim value hemlock__c__errno__einval(value unit)          { (void)unit; return Val_int(EINVAL); }
CAMLprim value hemlock__c__errno__enfile(value unit)          { (void)unit; return Val_int(ENFILE); }
CAMLprim value hemlock__c__errno__emfile(value unit)          { (void)unit; return Val_int(EMFILE); }
CAMLprim value hemlock__c__errno__enotty(value unit)          { (void)unit; return Val_int(ENOTTY); }
CAMLprim value hemlock__c__errno__etxtbsy(value unit)         { (void)unit; return Val_int(ETXTBSY); }
CAMLprim value hemlock__c__errno__efbig(value unit)           { (void)unit; return Val_int(EFBIG); }
CAMLprim value hemlock__c__errno__enospc(value unit)          { (void)unit; return Val_int(ENOSPC); }
CAMLprim value hemlock__c__errno__espipe(value unit)          { (void)unit; return Val_int(ESPIPE); }
CAMLprim value hemlock__c__errno__erofs(value unit)           { (void)unit; return Val_int(EROFS); }
CAMLprim value hemlock__c__errno__emlink(value unit)          { (void)unit; return Val_int(EMLINK); }
CAMLprim value hemlock__c__errno__epipe(value unit)           { (void)unit; return Val_int(EPIPE); }
CAMLprim value hemlock__c__errno__edom(value unit)            { (void)unit; return Val_int(EDOM); }
CAMLprim value hemlock__c__errno__erange(value unit)          { (void)unit; return Val_int(ERANGE); }
CAMLprim value hemlock__c__errno__edeadlk(value unit)         { (void)unit; return Val_int(EDEADLK); }
CAMLprim value hemlock__c__errno__enametoolong(value unit)    { (void)unit; return Val_int(ENAMETOOLONG); }
CAMLprim value hemlock__c__errno__enolck(value unit)          { (void)unit; return Val_int(ENOLCK); }
CAMLprim value hemlock__c__errno__enosys(value unit)          { (void)unit; return Val_int(ENOSYS); }
CAMLprim value hemlock__c__errno__enotempty(value unit)       { (void)unit; return Val_int(ENOTEMPTY); }
CAMLprim value hemlock__c__errno__eloop(value unit)           { (void)unit; return Val_int(ELOOP); }
CAMLprim value hemlock__c__errno__ewouldblock(value unit)     { (void)unit; return Val_int(EWOULDBLOCK); }
CAMLprim value hemlock__c__errno__enomsg(value unit)          { (void)unit; return Val_int(ENOMSG); }
CAMLprim value hemlock__c__errno__eidrm(value unit)           { (void)unit; return Val_int(EIDRM); }
CAMLprim value hemlock__c__errno__echrng(value unit)          { (void)unit; return Val_int(ECHRNG); }
CAMLprim value hemlock__c__errno__el2nsync(value unit)        { (void)unit; return Val_int(EL2NSYNC); }
CAMLprim value hemlock__c__errno__el3hlt(value unit)          { (void)unit; return Val_int(EL3HLT); }
CAMLprim value hemlock__c__errno__el3rst(value unit)          { (void)unit; return Val_int(EL3RST); }
CAMLprim value hemlock__c__errno__elnrng(value unit)          { (void)unit; return Val_int(ELNRNG); }
CAMLprim value hemlock__c__errno__eunatch(value unit)         { (void)unit; return Val_int(EUNATCH); }
CAMLprim value hemlock__c__errno__enocsi(value unit)          { (void)unit; return Val_int(ENOCSI); }
CAMLprim value hemlock__c__errno__el2hlt(value unit)          { (void)unit; return Val_int(EL2HLT); }
CAMLprim value hemlock__c__errno__ebade(value unit)           { (void)unit; return Val_int(EBADE); }
CAMLprim value hemlock__c__errno__ebadr(value unit)           { (void)unit; return Val_int(EBADR); }
CAMLprim value hemlock__c__errno__exfull(value unit)          { (void)unit; return Val_int(EXFULL); }
CAMLprim value hemlock__c__errno__enoano(value unit)          { (void)unit; return Val_int(ENOANO); }
CAMLprim value hemlock__c__errno__ebadrqc(value unit)         { (void)unit; return Val_int(EBADRQC); }
CAMLprim value hemlock__c__errno__ebadslt(value unit)         { (void)unit; return Val_int(EBADSLT); }
CAMLprim value hemlock__c__errno__edeadlock(value unit)       { (void)unit; return Val_int(EDEADLOCK); }
CAMLprim value hemlock__c__errno__ebfont(value unit)          { (void)unit; return Val_int(EBFONT); }
CAMLprim value hemlock__c__errno__enostr(value unit)          { (void)unit; return Val_int(ENOSTR); }
CAMLprim value hemlock__c__errno__enodata(value unit)         { (void)unit; return Val_int(ENODATA); }
CAMLprim value hemlock__c__errno__etime(value unit)           { (void)unit; return Val_int(ETIME); }
CAMLprim value hemlock__c__errno__enosr(value unit)           { (void)unit; return Val_int(ENOSR); }
CAMLprim value hemlock__c__errno__enonet(value unit)          { (void)unit; return Val_int(ENONET); }
CAMLprim value hemlock__c__errno__enopkg(value unit)          { (void)unit; return Val_int(ENOPKG); }
CAMLprim value hemlock__c__errno__eremote(value unit)         { (void)unit; return Val_int(EREMOTE); }
CAMLprim value hemlock__c__errno__enolink(value unit)         { (void)unit; return Val_int(ENOLINK); }
CAMLprim value hemlock__c__errno__eadv(value unit)            { (void)unit; return Val_int(EADV); }
CAMLprim value hemlock__c__errno__esrmnt(value unit)          { (void)unit; return Val_int(ESRMNT); }
CAMLprim value hemlock__c__errno__ecomm(value unit)           { (void)unit; return Val_int(ECOMM); }
CAMLprim value hemlock__c__errno__eproto(value unit)          { (void)unit; return Val_int(EPROTO); }
CAMLprim value hemlock__c__errno__emultihop(value unit)       { (void)unit; return Val_int(EMULTIHOP); }
CAMLprim value hemlock__c__errno__edotdot(value unit)         { (void)unit; return Val_int(EDOTDOT); }
CAMLprim value hemlock__c__errno__ebadmsg(value unit)         { (void)unit; return Val_int(EBADMSG); }
CAMLprim value hemlock__c__errno__eoverflow(value unit)       { (void)unit; return Val_int(EOVERFLOW); }
CAMLprim value hemlock__c__errno__enotuniq(value unit)        { (void)unit; return Val_int(ENOTUNIQ); }
CAMLprim value hemlock__c__errno__ebadfd(value unit)          { (void)unit; return Val_int(EBADFD); }
CAMLprim value hemlock__c__errno__eremchg(value unit)         { (void)unit; return Val_int(EREMCHG); }
CAMLprim value hemlock__c__errno__elibacc(value unit)         { (void)unit; return Val_int(ELIBACC); }
CAMLprim value hemlock__c__errno__elibbad(value unit)         { (void)unit; return Val_int(ELIBBAD); }
CAMLprim value hemlock__c__errno__elibscn(value unit)         { (void)unit; return Val_int(ELIBSCN); }
CAMLprim value hemlock__c__errno__elibmax(value unit)         { (void)unit; return Val_int(ELIBMAX); }
CAMLprim value hemlock__c__errno__elibexec(value unit)        { (void)unit; return Val_int(ELIBEXEC); }
CAMLprim value hemlock__c__errno__eilseq(value unit)          { (void)unit; return Val_int(EILSEQ); }
CAMLprim value hemlock__c__errno__erestart(value unit)        { (void)unit; return Val_int(ERESTART); }
CAMLprim value hemlock__c__errno__estrpipe(value unit)        { (void)unit; return Val_int(ESTRPIPE); }
CAMLprim value hemlock__c__errno__eusers(value unit)          { (void)unit; return Val_int(EUSERS); }
CAMLprim value hemlock__c__errno__enotsock(value unit)        { (void)unit; return Val_int(ENOTSOCK); }
CAMLprim value hemlock__c__errno__edestaddrreq(value unit)    { (void)unit; return Val_int(EDESTADDRREQ); }
CAMLprim value hemlock__c__errno__emsgsize(value unit)        { (void)unit; return Val_int(EMSGSIZE); }
CAMLprim value hemlock__c__errno__eprototype(value unit)      { (void)unit; return Val_int(EPROTOTYPE); }
CAMLprim value hemlock__c__errno__enoprotoopt(value unit)     { (void)unit; return Val_int(ENOPROTOOPT); }
CAMLprim value hemlock__c__errno__eprotonosupport(value unit) { (void)unit; return Val_int(EPROTONOSUPPORT); }
CAMLprim value hemlock__c__errno__esocktnosupport(value unit) { (void)unit; return Val_int(ESOCKTNOSUPPORT); }
CAMLprim value hemlock__c__errno__eopnotsupp(value unit)      { (void)unit; return Val_int(EOPNOTSUPP); }
CAMLprim value hemlock__c__errno__enotsup(value unit)         { (void)unit; return Val_int(ENOTSUP); }
CAMLprim value hemlock__c__errno__epfnosupport(value unit)    { (void)unit; return Val_int(EPFNOSUPPORT); }
CAMLprim value hemlock__c__errno__eafnosupport(value unit)    { (void)unit; return Val_int(EAFNOSUPPORT); }
CAMLprim value hemlock__c__errno__eaddrinuse(value unit)      { (void)unit; return Val_int(EADDRINUSE); }
CAMLprim value hemlock__c__errno__eaddrnotavail(value unit)   { (void)unit; return Val_int(EADDRNOTAVAIL); }
CAMLprim value hemlock__c__errno__enetdown(value unit)        { (void)unit; return Val_int(ENETDOWN); }
CAMLprim value hemlock__c__errno__enetunreach(value unit)     { (void)unit; return Val_int(ENETUNREACH); }
CAMLprim value hemlock__c__errno__enetreset(value unit)       { (void)unit; return Val_int(ENETRESET); }
CAMLprim value hemlock__c__errno__econnaborted(value unit)    { (void)unit; return Val_int(ECONNABORTED); }
CAMLprim value hemlock__c__errno__econnreset(value unit)      { (void)unit; return Val_int(ECONNRESET); }
CAMLprim value hemlock__c__errno__enobufs(value unit)         { (void)unit; return Val_int(ENOBUFS); }
CAMLprim value hemlock__c__errno__eisconn(value unit)         { (void)unit; return Val_int(EISCONN); }
CAMLprim value hemlock__c__errno__enotconn(value unit)        { (void)unit; return Val_int(ENOTCONN); }
CAMLprim value hemlock__c__errno__eshutdown(value unit)       { (void)unit; return Val_int(ESHUTDOWN); }
CAMLprim value hemlock__c__errno__etoomanyrefs(value unit)    { (void)unit; return Val_int(ETOOMANYREFS); }
CAMLprim value hemlock__c__errno__etimedout(value unit)       { (void)unit; return Val_int(ETIMEDOUT); }
CAMLprim value hemlock__c__errno__econnrefused(value unit)    { (void)unit; return Val_int(ECONNREFUSED); }
CAMLprim value hemlock__c__errno__ehostdown(value unit)       { (void)unit; return Val_int(EHOSTDOWN); }
CAMLprim value hemlock__c__errno__ehostunreach(value unit)    { (void)unit; return Val_int(EHOSTUNREACH); }
CAMLprim value hemlock__c__errno__ealready(value unit)        { (void)unit; return Val_int(EALREADY); }
CAMLprim value hemlock__c__errno__einprogress(value unit)     { (void)unit; return Val_int(EINPROGRESS); }
CAMLprim value hemlock__c__errno__estale(value unit)          { (void)unit; return Val_int(ESTALE); }
CAMLprim value hemlock__c__errno__euclean(value unit)         { (void)unit; return Val_int(EUCLEAN); }
CAMLprim value hemlock__c__errno__enotnam(value unit)         { (void)unit; return Val_int(ENOTNAM); }
CAMLprim value hemlock__c__errno__enavail(value unit)         { (void)unit; return Val_int(ENAVAIL); }
CAMLprim value hemlock__c__errno__eisnam(value unit)          { (void)unit; return Val_int(EISNAM); }
CAMLprim value hemlock__c__errno__eremoteio(value unit)       { (void)unit; return Val_int(EREMOTEIO); }
CAMLprim value hemlock__c__errno__edquot(value unit)          { (void)unit; return Val_int(EDQUOT); }
CAMLprim value hemlock__c__errno__enomedium(value unit)       { (void)unit; return Val_int(ENOMEDIUM); }
CAMLprim value hemlock__c__errno__emediumtype(value unit)     { (void)unit; return Val_int(EMEDIUMTYPE); }
CAMLprim value hemlock__c__errno__ecanceled(value unit)       { (void)unit; return Val_int(ECANCELED); }
CAMLprim value hemlock__c__errno__enokey(value unit)          { (void)unit; return Val_int(ENOKEY); }
CAMLprim value hemlock__c__errno__ekeyexpired(value unit)     { (void)unit; return Val_int(EKEYEXPIRED); }
CAMLprim value hemlock__c__errno__ekeyrevoked(value unit)     { (void)unit; return Val_int(EKEYREVOKED); }
CAMLprim value hemlock__c__errno__ekeyrejected(value unit)    { (void)unit; return Val_int(EKEYREJECTED); }
CAMLprim value hemlock__c__errno__eownerdead(value unit)      { (void)unit; return Val_int(EOWNERDEAD); }
CAMLprim value hemlock__c__errno__enotrecoverable(value unit) { (void)unit; return Val_int(ENOTRECOVERABLE); }
CAMLprim value hemlock__c__errno__erfkill(value unit)         { (void)unit; return Val_int(ERFKILL); }
CAMLprim value hemlock__c__errno__ehwpoison(value unit)       { (void)unit; return Val_int(EHWPOISON); }
