type t = int


external eperm           : unit -> t = "hemlock__c__errno__eperm"
external enoent          : unit -> t = "hemlock__c__errno__enoent"
external esrch           : unit -> t = "hemlock__c__errno__esrch"
external eintr           : unit -> t = "hemlock__c__errno__eintr"
external eio             : unit -> t = "hemlock__c__errno__eio"
external enxio           : unit -> t = "hemlock__c__errno__enxio"
external e2big           : unit -> t = "hemlock__c__errno__e2big"
external enoexec         : unit -> t = "hemlock__c__errno__enoexec"
external ebadf           : unit -> t = "hemlock__c__errno__ebadf"
external echild          : unit -> t = "hemlock__c__errno__echild"
external eagain          : unit -> t = "hemlock__c__errno__eagain"
external enomem          : unit -> t = "hemlock__c__errno__enomem"
external eacces          : unit -> t = "hemlock__c__errno__eacces"
external efault          : unit -> t = "hemlock__c__errno__efault"
external enotblk         : unit -> t = "hemlock__c__errno__enotblk"
external ebusy           : unit -> t = "hemlock__c__errno__ebusy"
external eexist          : unit -> t = "hemlock__c__errno__eexist"
external exdev           : unit -> t = "hemlock__c__errno__exdev"
external enodev          : unit -> t = "hemlock__c__errno__enodev"
external enotdir         : unit -> t = "hemlock__c__errno__enotdir"
external eisdir          : unit -> t = "hemlock__c__errno__eisdir"
external einval          : unit -> t = "hemlock__c__errno__einval"
external enfile          : unit -> t = "hemlock__c__errno__enfile"
external emfile          : unit -> t = "hemlock__c__errno__emfile"
external enotty          : unit -> t = "hemlock__c__errno__enotty"
external etxtbsy         : unit -> t = "hemlock__c__errno__etxtbsy"
external efbig           : unit -> t = "hemlock__c__errno__efbig"
external enospc          : unit -> t = "hemlock__c__errno__enospc"
external espipe          : unit -> t = "hemlock__c__errno__espipe"
external erofs           : unit -> t = "hemlock__c__errno__erofs"
external emlink          : unit -> t = "hemlock__c__errno__emlink"
external epipe           : unit -> t = "hemlock__c__errno__epipe"
external edom            : unit -> t = "hemlock__c__errno__edom"
external erange          : unit -> t = "hemlock__c__errno__erange"
external edeadlk         : unit -> t = "hemlock__c__errno__edeadlk"
external enametoolong    : unit -> t = "hemlock__c__errno__enametoolong"
external enolck          : unit -> t = "hemlock__c__errno__enolck"
external enosys          : unit -> t = "hemlock__c__errno__enosys"
external enotempty       : unit -> t = "hemlock__c__errno__enotempty"
external eloop           : unit -> t = "hemlock__c__errno__eloop"
external ewouldblock     : unit -> t = "hemlock__c__errno__ewouldblock"
external enomsg          : unit -> t = "hemlock__c__errno__enomsg"
external eidrm           : unit -> t = "hemlock__c__errno__eidrm"
external echrng          : unit -> t = "hemlock__c__errno__echrng"
external el2nsync        : unit -> t = "hemlock__c__errno__el2nsync"
external el3hlt          : unit -> t = "hemlock__c__errno__el3hlt"
external el3rst          : unit -> t = "hemlock__c__errno__el3rst"
external elnrng          : unit -> t = "hemlock__c__errno__elnrng"
external eunatch         : unit -> t = "hemlock__c__errno__eunatch"
external enocsi          : unit -> t = "hemlock__c__errno__enocsi"
external el2hlt          : unit -> t = "hemlock__c__errno__el2hlt"
external ebade           : unit -> t = "hemlock__c__errno__ebade"
external ebadr           : unit -> t = "hemlock__c__errno__ebadr"
external exfull          : unit -> t = "hemlock__c__errno__exfull"
external enoano          : unit -> t = "hemlock__c__errno__enoano"
external ebadrqc         : unit -> t = "hemlock__c__errno__ebadrqc"
external ebadslt         : unit -> t = "hemlock__c__errno__ebadslt"
external edeadlock       : unit -> t = "hemlock__c__errno__edeadlock"
external ebfont          : unit -> t = "hemlock__c__errno__ebfont"
external enostr          : unit -> t = "hemlock__c__errno__enostr"
external enodata         : unit -> t = "hemlock__c__errno__enodata"
external etime           : unit -> t = "hemlock__c__errno__etime"
external enosr           : unit -> t = "hemlock__c__errno__enosr"
external enonet          : unit -> t = "hemlock__c__errno__enonet"
external enopkg          : unit -> t = "hemlock__c__errno__enopkg"
external eremote         : unit -> t = "hemlock__c__errno__eremote"
external enolink         : unit -> t = "hemlock__c__errno__enolink"
external eadv            : unit -> t = "hemlock__c__errno__eadv"
external esrmnt          : unit -> t = "hemlock__c__errno__esrmnt"
external ecomm           : unit -> t = "hemlock__c__errno__ecomm"
external eproto          : unit -> t = "hemlock__c__errno__eproto"
external emultihop       : unit -> t = "hemlock__c__errno__emultihop"
external edotdot         : unit -> t = "hemlock__c__errno__edotdot"
external ebadmsg         : unit -> t = "hemlock__c__errno__ebadmsg"
external eoverflow       : unit -> t = "hemlock__c__errno__eoverflow"
external enotuniq        : unit -> t = "hemlock__c__errno__enotuniq"
external ebadfd          : unit -> t = "hemlock__c__errno__ebadfd"
external eremchg         : unit -> t = "hemlock__c__errno__eremchg"
external elibacc         : unit -> t = "hemlock__c__errno__elibacc"
external elibbad         : unit -> t = "hemlock__c__errno__elibbad"
external elibscn         : unit -> t = "hemlock__c__errno__elibscn"
external elibmax         : unit -> t = "hemlock__c__errno__elibmax"
external elibexec        : unit -> t = "hemlock__c__errno__elibexec"
external eilseq          : unit -> t = "hemlock__c__errno__eilseq"
external erestart        : unit -> t = "hemlock__c__errno__erestart"
external estrpipe        : unit -> t = "hemlock__c__errno__estrpipe"
external eusers          : unit -> t = "hemlock__c__errno__eusers"
external enotsock        : unit -> t = "hemlock__c__errno__enotsock"
external edestaddrreq    : unit -> t = "hemlock__c__errno__edestaddrreq"
external emsgsize        : unit -> t = "hemlock__c__errno__emsgsize"
external eprototype      : unit -> t = "hemlock__c__errno__eprototype"
external enoprotoopt     : unit -> t = "hemlock__c__errno__enoprotoopt"
external eprotonosupport : unit -> t = "hemlock__c__errno__eprotonosupport"
external esocktnosupport : unit -> t = "hemlock__c__errno__esocktnosupport"
external eopnotsupp      : unit -> t = "hemlock__c__errno__eopnotsupp"
external enotsup         : unit -> t = "hemlock__c__errno__enotsup"
external epfnosupport    : unit -> t = "hemlock__c__errno__epfnosupport"
external eafnosupport    : unit -> t = "hemlock__c__errno__eafnosupport"
external eaddrinuse      : unit -> t = "hemlock__c__errno__eaddrinuse"
external eaddrnotavail   : unit -> t = "hemlock__c__errno__eaddrnotavail"
external enetdown        : unit -> t = "hemlock__c__errno__enetdown"
external enetunreach     : unit -> t = "hemlock__c__errno__enetunreach"
external enetreset       : unit -> t = "hemlock__c__errno__enetreset"
external econnaborted    : unit -> t = "hemlock__c__errno__econnaborted"
external econnreset      : unit -> t = "hemlock__c__errno__econnreset"
external enobufs         : unit -> t = "hemlock__c__errno__enobufs"
external eisconn         : unit -> t = "hemlock__c__errno__eisconn"
external enotconn        : unit -> t = "hemlock__c__errno__enotconn"
external eshutdown       : unit -> t = "hemlock__c__errno__eshutdown"
external etoomanyrefs    : unit -> t = "hemlock__c__errno__etoomanyrefs"
external etimedout       : unit -> t = "hemlock__c__errno__etimedout"
external econnrefused    : unit -> t = "hemlock__c__errno__econnrefused"
external ehostdown       : unit -> t = "hemlock__c__errno__ehostdown"
external ehostunreach    : unit -> t = "hemlock__c__errno__ehostunreach"
external ealready        : unit -> t = "hemlock__c__errno__ealready"
external einprogress     : unit -> t = "hemlock__c__errno__einprogress"
external estale          : unit -> t = "hemlock__c__errno__estale"
external euclean         : unit -> t = "hemlock__c__errno__euclean"
external enotnam         : unit -> t = "hemlock__c__errno__enotnam"
external enavail         : unit -> t = "hemlock__c__errno__enavail"
external eisnam          : unit -> t = "hemlock__c__errno__eisnam"
external eremoteio       : unit -> t = "hemlock__c__errno__eremoteio"
external edquot          : unit -> t = "hemlock__c__errno__edquot"
external enomedium       : unit -> t = "hemlock__c__errno__enomedium"
external emediumtype     : unit -> t = "hemlock__c__errno__emediumtype"
external ecanceled       : unit -> t = "hemlock__c__errno__ecanceled"
external enokey          : unit -> t = "hemlock__c__errno__enokey"
external ekeyexpired     : unit -> t = "hemlock__c__errno__ekeyexpired"
external ekeyrevoked     : unit -> t = "hemlock__c__errno__ekeyrevoked"
external ekeyrejected    : unit -> t = "hemlock__c__errno__ekeyrejected"
external eownerdead      : unit -> t = "hemlock__c__errno__eownerdead"
external enotrecoverable : unit -> t = "hemlock__c__errno__enotrecoverable"
external erfkill         : unit -> t = "hemlock__c__errno__erfkill"
external ehwpoison       : unit -> t = "hemlock__c__errno__ehwpoison"

let eperm           = eperm ()
let enoent          = enoent ()
let esrch           = esrch ()
let eintr           = eintr ()
let eio             = eio ()
let enxio           = enxio ()
let e2big           = e2big ()
let enoexec         = enoexec ()
let ebadf           = ebadf ()
let echild          = echild ()
let eagain          = eagain ()
let enomem          = enomem ()
let eacces          = eacces ()
let efault          = efault ()
let enotblk         = enotblk ()
let ebusy           = ebusy ()
let eexist          = eexist ()
let exdev           = exdev ()
let enodev          = enodev ()
let enotdir         = enotdir ()
let eisdir          = eisdir ()
let einval          = einval ()
let enfile          = enfile ()
let emfile          = emfile ()
let enotty          = enotty ()
let etxtbsy         = etxtbsy ()
let efbig           = efbig ()
let enospc          = enospc ()
let espipe          = espipe ()
let erofs           = erofs ()
let emlink          = emlink ()
let epipe           = epipe ()
let edom            = edom ()
let erange          = erange ()
let edeadlk         = edeadlk ()
let enametoolong    = enametoolong ()
let enolck          = enolck ()
let enosys          = enosys ()
let enotempty       = enotempty ()
let eloop           = eloop ()
let ewouldblock     = ewouldblock ()
let enomsg          = enomsg ()
let eidrm           = eidrm ()
let echrng          = echrng ()
let el2nsync        = el2nsync ()
let el3hlt          = el3hlt ()
let el3rst          = el3rst ()
let elnrng          = elnrng ()
let eunatch         = eunatch ()
let enocsi          = enocsi ()
let el2hlt          = el2hlt ()
let ebade           = ebade ()
let ebadr           = ebadr ()
let exfull          = exfull ()
let enoano          = enoano ()
let ebadrqc         = ebadrqc ()
let ebadslt         = ebadslt ()
let edeadlock       = edeadlock ()
let ebfont          = ebfont ()
let enostr          = enostr ()
let enodata         = enodata ()
let etime           = etime ()
let enosr           = enosr ()
let enonet          = enonet ()
let enopkg          = enopkg ()
let eremote         = eremote ()
let enolink         = enolink ()
let eadv            = eadv ()
let esrmnt          = esrmnt ()
let ecomm           = ecomm ()
let eproto          = eproto ()
let emultihop       = emultihop ()
let edotdot         = edotdot ()
let ebadmsg         = ebadmsg ()
let eoverflow       = eoverflow ()
let enotuniq        = enotuniq ()
let ebadfd          = ebadfd ()
let eremchg         = eremchg ()
let elibacc         = elibacc ()
let elibbad         = elibbad ()
let elibscn         = elibscn ()
let elibmax         = elibmax ()
let elibexec        = elibexec ()
let eilseq          = eilseq ()
let erestart        = erestart ()
let estrpipe        = estrpipe ()
let eusers          = eusers ()
let enotsock        = enotsock ()
let edestaddrreq    = edestaddrreq ()
let emsgsize        = emsgsize ()
let eprototype      = eprototype ()
let enoprotoopt     = enoprotoopt ()
let eprotonosupport = eprotonosupport ()
let esocktnosupport = esocktnosupport ()
let eopnotsupp      = eopnotsupp ()
let enotsup         = enotsup ()
let epfnosupport    = epfnosupport ()
let eafnosupport    = eafnosupport ()
let eaddrinuse      = eaddrinuse ()
let eaddrnotavail   = eaddrnotavail ()
let enetdown        = enetdown ()
let enetunreach     = enetunreach ()
let enetreset       = enetreset ()
let econnaborted    = econnaborted ()
let econnreset      = econnreset ()
let enobufs         = enobufs ()
let eisconn         = eisconn ()
let enotconn        = enotconn ()
let eshutdown       = eshutdown ()
let etoomanyrefs    = etoomanyrefs ()
let etimedout       = etimedout ()
let econnrefused    = econnrefused ()
let ehostdown       = ehostdown ()
let ehostunreach    = ehostunreach ()
let ealready        = ealready ()
let einprogress     = einprogress ()
let estale          = estale ()
let euclean         = euclean ()
let enotnam         = enotnam ()
let enavail         = enavail ()
let eisnam          = eisnam ()
let eremoteio       = eremoteio ()
let edquot          = edquot ()
let enomedium       = enomedium ()
let emediumtype     = emediumtype ()
let ecanceled       = ecanceled ()
let enokey          = enokey ()
let ekeyexpired     = ekeyexpired ()
let ekeyrevoked     = ekeyrevoked ()
let ekeyrejected    = ekeyrejected ()
let eownerdead      = eownerdead ()
let enotrecoverable = enotrecoverable ()
let erfkill         = erfkill ()
let ehwpoison       = ehwpoison ()
