type t

val eperm           : t  (* EPERM: Operation not permitted *)
val enoent          : t  (* ENOENT: No such file or directory *)
val esrch           : t  (* ESRCH: No such process *)
val eintr           : t  (* EINTR: Interrupted system call *)
val eio             : t  (* EIO: I/O error *)
val enxio           : t  (* ENXIO: No such device or address *)
val e2big           : t  (* E2BIG: Argument list too long *)
val enoexec         : t  (* ENOEXEC: Exec format error *)
val ebadf           : t  (* EBADF: Bad file number *)
val echild          : t  (* ECHILD: No child processes *)
val eagain          : t  (* EAGAIN: Try again *)
val enomem          : t  (* ENOMEM: Out of memory *)
val eacces          : t  (* EACCES: Permission denied *)
val efault          : t  (* EFAULT: Bad address *)
val enotblk         : t  (* ENOTBLK: Block device required *)
val ebusy           : t  (* EBUSY: Device or resource busy *)
val eexist          : t  (* EEXIST: File exists *)
val exdev           : t  (* EXDEV: Cross-device link *)
val enodev          : t  (* ENODEV: No such device *)
val enotdir         : t  (* ENOTDIR: Not a directory *)
val eisdir          : t  (* EISDIR: Is a directory *)
val einval          : t  (* EINVAL: Invalid argument *)
val enfile          : t  (* ENFILE: File table overflow *)
val emfile          : t  (* EMFILE: Too many open files *)
val enotty          : t  (* ENOTTY: Not a typewriter *)
val etxtbsy         : t  (* ETXTBSY: Text file busy *)
val efbig           : t  (* EFBIG: File too large *)
val enospc          : t  (* ENOSPC: No space left on device *)
val espipe          : t  (* ESPIPE: Illegal seek *)
val erofs           : t  (* EROFS: Read-only file system *)
val emlink          : t  (* EMLINK: Too many links *)
val epipe           : t  (* EPIPE: Broken pipe *)
val edom            : t  (* EDOM: Math argument out of domain of func *)
val erange          : t  (* ERANGE: Math result not representable *)
val edeadlk         : t  (* EDEADLK: Resource deadlock would occur *)
val enametoolong    : t  (* ENAMETOOLONG: File name too long *)
val enolck          : t  (* ENOLCK: No record locks available *)
val enosys          : t  (* ENOSYS: Invalid system call number *)
val enotempty       : t  (* ENOTEMPTY: Directory not empty *)
val eloop           : t  (* ELOOP: Too many symbolic links encountered *)
val ewouldblock     : t  (* EWOULDBLOCK: Operation would block (= EAGAIN) *)
val enomsg          : t  (* ENOMSG: No message of desired type *)
val eidrm           : t  (* EIDRM: Identifier removed *)
val echrng          : t  (* ECHRNG: Channel number out of range *)
val el2nsync        : t  (* EL2NSYNC: Level 2 not synchronized *)
val el3hlt          : t  (* EL3HLT: Level 3 halted *)
val el3rst          : t  (* EL3RST: Level 3 reset *)
val elnrng          : t  (* ELNRNG: Link number out of range *)
val eunatch         : t  (* EUNATCH: Protocol driver not attached *)
val enocsi          : t  (* ENOCSI: No CSI structure available *)
val el2hlt          : t  (* EL2HLT: Level 2 halted *)
val ebade           : t  (* EBADE: Invalid exchange *)
val ebadr           : t  (* EBADR: Invalid request descriptor *)
val exfull          : t  (* EXFULL: Exchange full *)
val enoano          : t  (* ENOANO: No anode *)
val ebadrqc         : t  (* EBADRQC: Invalid request code *)
val ebadslt         : t  (* EBADSLT: Invalid slot *)
val edeadlock       : t  (* EDEADLOCK: Resource deadlock would occur (= EDEADLK) *)
val ebfont          : t  (* EBFONT: Bad font file format *)
val enostr          : t  (* ENOSTR: Device not a stream *)
val enodata         : t  (* ENODATA: No data available *)
val etime           : t  (* ETIME: Timer expired *)
val enosr           : t  (* ENOSR: Out of streams resources *)
val enonet          : t  (* ENONET: Machine is not on the network *)
val enopkg          : t  (* ENOPKG: Package not installed *)
val eremote         : t  (* EREMOTE: Object is remote *)
val enolink         : t  (* ENOLINK: Link has been severed *)
val eadv            : t  (* EADV: Advertise error *)
val esrmnt          : t  (* ESRMNT: Srmount error *)
val ecomm           : t  (* ECOMM: Communication error on send *)
val eproto          : t  (* EPROTO: Protocol error *)
val emultihop       : t  (* EMULTIHOP: Multihop attempted *)
val edotdot         : t  (* EDOTDOT: RFS specific error *)
val ebadmsg         : t  (* EBADMSG: Not a data message *)
val eoverflow       : t  (* EOVERFLOW: Value too large for defined data type *)
val enotuniq        : t  (* ENOTUNIQ: Name not unique on network *)
val ebadfd          : t  (* EBADFD: File descriptor in bad state *)
val eremchg         : t  (* EREMCHG: Remote address changed *)
val elibacc         : t  (* ELIBACC: Can not access a needed shared library *)
val elibbad         : t  (* ELIBBAD: Accessing a corrupted shared library *)
val elibscn         : t  (* ELIBSCN: .lib section in a.out corrupted *)
val elibmax         : t  (* ELIBMAX: Attempting to link in too many shared libraries *)
val elibexec        : t  (* ELIBEXEC: Cannot exec a shared library directly *)
val eilseq          : t  (* EILSEQ: Illegal byte sequence *)
val erestart        : t  (* ERESTART: Interrupted system call should be restarted *)
val estrpipe        : t  (* ESTRPIPE: Streams pipe error *)
val eusers          : t  (* EUSERS: Too many users *)
val enotsock        : t  (* ENOTSOCK: Socket operation on non-socket *)
val edestaddrreq    : t  (* EDESTADDRREQ: Destination address required *)
val emsgsize        : t  (* EMSGSIZE: Message too long *)
val eprototype      : t  (* EPROTOTYPE: Protocol wrong type for socket *)
val enoprotoopt     : t  (* ENOPROTOOPT: Protocol not available *)
val eprotonosupport : t  (* EPROTONOSUPPORT: Protocol not supported *)
val esocktnosupport : t  (* ESOCKTNOSUPPORT: Socket type not supported *)
val eopnotsupp      : t  (* EOPNOTSUPP: Operation not supported on transport endpoint *)
val enotsup         : t  (* ENOTSUP: Operation not supported (= EOPNOTSUPP) *)
val epfnosupport    : t  (* EPFNOSUPPORT: Protocol family not supported *)
val eafnosupport    : t  (* EAFNOSUPPORT: Address family not supported by protocol *)
val eaddrinuse      : t  (* EADDRINUSE: Address already in use *)
val eaddrnotavail   : t  (* EADDRNOTAVAIL: Cannot assign requested address *)
val enetdown        : t  (* ENETDOWN: Network is down *)
val enetunreach     : t  (* ENETUNREACH: Network is unreachable *)
val enetreset       : t  (* ENETRESET: Network dropped connection because of reset *)
val econnaborted    : t  (* ECONNABORTED: Software caused connection abort *)
val econnreset      : t  (* ECONNRESET: Connection reset by peer *)
val enobufs         : t  (* ENOBUFS: No buffer space available *)
val eisconn         : t  (* EISCONN: Transport endpoint is already connected *)
val enotconn        : t  (* ENOTCONN: Transport endpoint is not connected *)
val eshutdown       : t  (* ESHUTDOWN: Cannot send after transport endpoint shutdown *)
val etoomanyrefs    : t  (* ETOOMANYREFS: Too many references: cannot splice *)
val etimedout       : t  (* ETIMEDOUT: Connection timed out *)
val econnrefused    : t  (* ECONNREFUSED: Connection refused *)
val ehostdown       : t  (* EHOSTDOWN: Host is down *)
val ehostunreach    : t  (* EHOSTUNREACH: No route to host *)
val ealready        : t  (* EALREADY: Operation already in progress *)
val einprogress     : t  (* EINPROGRESS: Operation now in progress *)
val estale          : t  (* ESTALE: Stale file handle *)
val euclean         : t  (* EUCLEAN: Structure needs cleaning *)
val enotnam         : t  (* ENOTNAM: Not a XENIX named type file *)
val enavail         : t  (* ENAVAIL: No XENIX semaphores available *)
val eisnam          : t  (* EISNAM: Is a named type file *)
val eremoteio       : t  (* EREMOTEIO: Remote I/O error *)
val edquot          : t  (* EDQUOT: Quota exceeded *)
val enomedium       : t  (* ENOMEDIUM: No medium found *)
val emediumtype     : t  (* EMEDIUMTYPE: Wrong medium type *)
val ecanceled       : t  (* ECANCELED: Operation Canceled *)
val enokey          : t  (* ENOKEY: Required key not available *)
val ekeyexpired     : t  (* EKEYEXPIRED: Key has expired *)
val ekeyrevoked     : t  (* EKEYREVOKED: Key has been revoked *)
val ekeyrejected    : t  (* EKEYREJECTED: Key was rejected by service *)
val eownerdead      : t  (* EOWNERDEAD: Owner died *)
val enotrecoverable : t  (* ENOTRECOVERABLE: State not recoverable *)
val erfkill         : t  (* ERFKILL: Operation not possible due to RF-kill *)
val ehwpoison       : t  (* EHWPOISON: Memory page has hardware error *)
