#define _GNU_SOURCE // For O_DIRECT, O_NOATIME, O_PATH O_TMPFILE
#define _LARGEFILE64_SOURCE // For O_LARGEFILE

#include <fcntl.h>

#define CAML_NAME_SPACE
#include <caml/alloc.h>

// Export underlying ctype values for Hemlock.Os.Linux.Open.Flag.t.
#define HEMLOCK_OS_LINUX_OPEN_FLAG_T(FLAG) \
CAMLprim value hemlock_os_linux_open_flag_get_ ## FLAG (value) { \
    return caml_copy_int64(FLAG); \
}

HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_RDONLY)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_RDWR)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_WRONLY)

HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_CLOEXEC)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_CREAT)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_DIRECTORY)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_EXCL)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_NOCTTY)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_NOFOLLOW)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_TMPFILE)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_TRUNC)

HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_APPEND)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_ASYNC)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_DIRECT)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_DSYNC)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_LARGEFILE)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_NDELAY)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_NOATIME)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_NONBLOCK)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_PATH)
HEMLOCK_OS_LINUX_OPEN_FLAG_T(O_SYNC)

#undef HEMLOCK_OS_LINUX_OPEN_FLAG_T
