#include <fcntl.h>

#define CAML_NAME_SPACE
#include <caml/alloc.h>

// Export underlying ctype values for File.Open.Mode.t.
#define HEMLOCK_OS_LINUX_OPEN_MODE_T(MODE) \
CAMLprim value hemlock_os_linux_open_mode_t_ ## MODE () { \
    return caml_copy_int64(MODE); \
}

HEMLOCK_OS_LINUX_OPEN_MODE_T(S_ISUID)
HEMLOCK_OS_LINUX_OPEN_MODE_T(S_ISGID)
HEMLOCK_OS_LINUX_OPEN_MODE_T(S_ISVTX)

HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IRWXU)
HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IRUSR)
HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IWUSR)
HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IXUSR)

HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IRWXG)
HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IRGRP)
HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IWGRP)
HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IXGRP)

HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IRWXO)
HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IROTH)
HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IWOTH)
HEMLOCK_OS_LINUX_OPEN_MODE_T(S_IXOTH)

#undef HEMLOCK_OS_LINUX_OPEN_MODE
