name: Test

#on: pull_request
on: push

jobs:
  run:
    name: Test
    #runs-on: ubuntu-24.04
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: docker_compose_build_tested
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HM_PUSH_SHA: ${{ github.event.pull_request.head.sha }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
      run: docker compose build tested
